import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../repositories/admin_repository.dart';
import '../../models/user_model.dart';
import '../../models/academic_models.dart';

class UserFormPage extends StatefulWidget {
  final String role;
  final String roleTitle;
  final UserModel? user; // If null, it's Add mode. If not null, it's Edit mode.

  const UserFormPage({super.key, required this.role, required this.roleTitle, this.user});

  @override
  State<UserFormPage> createState() => _UserFormPageState();
}

class _UserFormPageState extends State<UserFormPage> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _usernameController;
  late TextEditingController _nameController;
  late TextEditingController _passwordController;
  bool _isLoading = false;
  
  List<MajorModel> _majors = [];
  String? _selectedMajorId;

  @override
  void initState() {
    super.initState();
    _usernameController = TextEditingController(text: widget.user?.nimOrNip ?? '');
    _nameController = TextEditingController(text: widget.user?.name ?? '');
    _passwordController = TextEditingController(); 
    _selectedMajorId = widget.user?.majorId;
    
    if (widget.role == 'mahasiswa') {
      _fetchMajors();
    }
  }

  Future<void> _fetchMajors() async {
    final repo = Provider.of<AdminRepository>(context, listen: false);
    final majors = await repo.getMajors();
    if (mounted) {
      setState(() {
        _majors = majors;
      });
    }
  }

  @override
  void dispose() {
    _usernameController.dispose();
    _nameController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  Future<void> _saveUser() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);
    final repo = Provider.of<AdminRepository>(context, listen: false);
    
    bool success;
    if (widget.user == null) {
      // Create
      final newUser = UserModel(
        id: '', // ID generated by DB
        email: _usernameController.text, // Using username as email/identifier
        name: _nameController.text,
        role: widget.role,
        nimOrNip: _usernameController.text,
        majorId: _selectedMajorId,
      );
      success = await repo.createUser(newUser, _passwordController.text);
    } else {
      // Update
      final updatedUser = UserModel(
        id: widget.user!.id,
        email: _usernameController.text,
        name: _nameController.text,
        role: widget.role,
        nimOrNip: _usernameController.text,
        majorId: _selectedMajorId,
      );
      success = await repo.updateUser(updatedUser, _passwordController.text.isEmpty ? null : _passwordController.text);
    }

    setState(() => _isLoading = false);

    if (success && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Data berhasil disimpan')),
      );
      Navigator.pop(context);
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Gagal menyimpan data')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEdit = widget.user != null;
    
    return Scaffold(
      appBar: AppBar(
        title: Text(isEdit ? 'Edit ${widget.roleTitle}' : 'Tambah ${widget.roleTitle}', style: GoogleFonts.poppins(fontWeight: FontWeight.w600)),
        backgroundColor: Colors.white,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _usernameController,
                decoration: InputDecoration(
                  labelText: widget.role == 'mahasiswa' ? 'NIM' : (widget.role == 'dosen' ? 'NIP' : 'Username'),
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  prefixIcon: const Icon(Icons.badge),
                ),
                validator: (value) => value == null || value.isEmpty ? 'Wajib diisi' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(
                  labelText: 'Nama Lengkap',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  prefixIcon: const Icon(Icons.person),
                ),
                validator: (value) => value == null || value.isEmpty ? 'Wajib diisi' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _passwordController,
                obscureText: true,
                decoration: InputDecoration(
                  labelText: isEdit ? 'Password (Kosongkan jika tidak ubah)' : 'Password',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  prefixIcon: const Icon(Icons.lock),
                ),
                validator: (value) {
                  if (!isEdit && (value == null || value.isEmpty)) {
                    return 'Password wajib diisi untuk user baru';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 32),
                const SizedBox(height: 16),
                if (widget.role == 'mahasiswa') ...[
                  DropdownButtonFormField<String>(
                    value: _selectedMajorId,
                    decoration: InputDecoration(
                      labelText: 'Jurusan',
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                      prefixIcon: const Icon(Icons.school),
                    ),
                    items: _majors.map((major) {
                      return DropdownMenuItem(
                        value: major.id,
                        child: Text(major.name),
                      );
                    }).toList(),
                    onChanged: (value) {
                      setState(() => _selectedMajorId = value);
                    },
                    validator: (value) => value == null ? 'Wajib dipilih' : null,
                  ),
                  const SizedBox(height: 16),
                ],
                ElevatedButton(
                  onPressed: _isLoading ? null : _saveUser,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF667EEA),
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: _isLoading
                      ? const CircularProgressIndicator(color: Colors.white)
                      : Text(
                          'Simpan',
                          style: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600, color: Colors.white),
                        ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
